backend:
  name: github
  repo: kldeb/end-corona-virus

media_folder: static/assets
public_folder: /assets

collections:
  - name: updates
    label: Updates
    folder: src/markdown-pages/updates
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
